plugins {
    id 'java-library'
}

group = 'io.seoleir.engram'
version = '0.0.1-SNAPSHOT'
description = 'client'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':core')
    api project(':spi')
    implementation project(':runtime')
}
