plugins {
    id 'java'
    id 'java-library'
}

group = 'io.seoleir.engram'
version = '0.0.1-SNAPSHOT'
description = 'codec-cbor'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':core')
    implementation 'tools.jackson.dataformat:jackson-dataformat-cbor:3.2.2'
}