plugins {
    id 'java'
}

group = 'io.seoleir'
version = '0.0.1-SNAPSHOT'
description = 'examples'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':runtime')
    implementation project(':backend-memory')
    implementation project(':codec-cbor')
}
